### ISSUE TITLE
Reg Time Zones

### ISSUE THREAD

**Issue by tirupatihemanth** [nishanthvijayan/CoderCalendar#12]
if you can show contest timings based on time zones of the user that would be a great plus. Thank You

**Comment by nishanthvijayan** [comment]
This feature is already present in the extensions.The Android app currently supports IST only.I'm working on it.

**Comment by tirupatihemanth** [comment]
It says srm 660 begins on 11:00 am on June 4th. but it actually begins on 7:00am EDT which is not 11:00am IST

**Comment by nishanthvijayan** [comment]
![testing](https://cloud.githubusercontent.com/assets/7537349/7956738/d43dfc24-09ff-11e5-8ba9-20259bcf2784.png)
I don't seem to have that problem.Make sure that your timezone settings are correct.

**Comment by tirupatihemanth** [comment]
Thank You very much. It's my fault my system location was set wrong. Again thank you for a good extension and I am done with the issue
