### ISSUE TITLE
Add Caribbean Online Judge

### ISSUE THREAD

**Issue by davidjacobo** [nishanthvijayan/CoderCalendar#13]
Could you guys add caribbean online open contests?

**Comment by nishanthvijayan** [comment]
I'm on vacation right now.I'll look into it as soon as I get back.

**Comment by nishanthvijayan** [comment]
Do they have open contests? All 4 upcoming contests are private.

**Comment by davidjacobo** [comment]
Yeah they have open contests, 'Progressive Contests' are particularly fun

**Comment by davidjacobo** [comment]
Woops, didn't mean to press close
