### ISSUE TITLE
What API did you use? 

### ISSUE THREAD

**Issue by sandeepwww** [nishanthvijayan/CoderCalendar#16]
I was wondering what the source of this app is. From where does it get its schedule.?

**Comment by nishanthvijayan** [comment]
I have a backend running http://contesttrackerapi.herokuapp.com/ created using Python-Flask,the code of which is available under the backend/  folder of this repo.

**Comment by scoobybutter** [comment]
Can i use this api?

**Comment by nishanthvijayan** [comment]
@scoobybutter Sure, just make sure that you hit it at a reasonable rate.Also, if your project is going to be put on GitHub, it'd be cool if you could add a link back to this project.

**Comment by scoobybutter** [comment]
thank you sir... will do,for sure  :)

**Comment by shrutie** [comment]
Hey @nishanthvijayan ! Can I use your API too? I can deeplink your project on my GitHub readme. :)
