### ISSUE TITLE
remove a contest

### ISSUE THREAD

**Issue by nirajNijju** [nishanthvijayan/CoderCalendar#22]
There should be an option to remove a contest. like if I can remove projecteuler( of hackerRank ), it is a pseudo contest for next 9 year.

**Comment by nishanthvijayan** [comment]
Yes.I always planned to do this but never got around to actually implementing it.
Any pull requests in this regard is definitely welcome.

**Comment by nishanthvijayan** [comment]
@jainendra any ideas ?

**Comment by jainendra** [comment]
@nishanthvijayan Yeah I'll do it...

**Comment by nishanthvijayan** [comment]
This is done.
