### ISSUE TITLE
[Firefox] Port SDK add-on to WebExtension?

### ISSUE THREAD

**Issue by nishanthvijayan** [nishanthvijayan/CoderCalendar#37]

**Comment by ladderlogician** [comment]
I am working on porting to webextension.

**Comment by tarunz** [comment]
@nishanthvijayan Pull request 
https://github.com/nishanthvijayan/CoderCalendar/pull/56

**Comment by nishanthvijayan** [comment]
've updated the add-on to make it compatible with Firefox Quantum. Let me know if the issue is fixed.
https://addons.mozilla.org/en-US/firefox/addon/coder-calendar/
