### ISSUE TITLE
Add New Contest Platform

### ISSUE THREAD

**Issue by rofi93** [nishanthvijayan/CoderCalendar#38]
Please add new contest platform atcoder ( https://atcoder.jp/ ) and csacademy (https://csacademy.com/).

**Comment by rofi93** [comment]
I have scraped atcoder but i scraped it using java. couldn't do it using python.

**Comment by pratik1105** [comment]
Is anyone working on this ? If Yes, Excellent. If not, could anyone give me a quick guide as to the steps needed to do this so that I could put this together. I feel a great need for these 2 platforms.

**Comment by rofi93** [comment]
@pratik1105 CSAcademy doesn't provide end time or duration so we can't add that platform. I worked on Atcoder recently.

**Comment by praran26** [comment]
@rofi93 CSAcademy does show duration.

**Comment by rofi93** [comment]
@praran26 Can you give me link. I didn't find the duration in contest list page.

**Comment by rofi93** [comment]
@praran26 Got it. I will try to start working on it soon.

**Comment by rofi93** [comment]
Pull request #48

**Comment by nishanthvijayan** [comment]
Both AtCoder & CSAcademy contests are now available on CoderCalendar now. The project has been split up and moved to https://github.com/nishanthvijayan/CoderCalendar-API && https://github.com/nishanthvijayan/CoderCalendar-Extensions
