### ISSUE TITLE
TCO link is invalid

### ISSUE THREAD

**Issue by Ibrahim-Habib** [nishanthvijayan/CoderCalendar#5]
when I click on next TCO contest (which starts in next Saturday 9/5) it leads me to this [link](http://community.topcoder.com/tc?module=MatchDetails&rd=16434) which displays an error message !

**Comment by nishanthvijayan** [comment]
Aah..Generally SRM's have an overview page with a link like this
http://community.topcoder.com/stat?c=round_overview&er=5&rd=ID
where ID is the id of that SRM.
But TCO contests doesn't seem to have such a page,so I'll reroute all TCO contests to http://tco15.topcoder.com/algorithm/rules/
