### ISSUE TITLE
Request for addition fuctionality

### ISSUE THREAD

**Issue by madhur4127** [nishanthvijayan/CoderCalendar#51]
Atcoder of japan is also one of most rated websites please add it to the list.

**Comment by rofi93** [comment]
I have added Atcoder, but the pull request is pending since June 15.

**Comment by nishanthvijayan** [comment]
AtCoder contests are now available on CoderCalendar. @rofi93 Thanks for the contribution, but I've rewritten the entire frontend & backend. I added AtCoder in the rewrite. You can find the new backend API repo here: https://github.com/nishanthvijayan/CoderCalendar-API. 
I'm closing this issue
