### ISSUE TITLE
[Firefox] No more compatible with latest version.

### ISSUE THREAD

**Issue by aman935** [nishanthvijayan/CoderCalendar#54]
I was a regular user of your add-on. But, due to recent firefox upgrade. The extension was disabled by default. I cannot use it anymore. Will you please update it, so that it becomes usable.

**Comment by EmberCS15** [comment]
Same here. Please update the code so that it is compatible with FireFox Quantum.

**Comment by ladderlogician** [comment]
I am working on porting this extension to webextension

**Comment by tarunz** [comment]
@nishanthvijayan Pull request https://github.com/nishanthvijayan/CoderCalendar/pulls

**Comment by tarunz** [comment]
@nishanthvijayan Pull request 
https://github.com/nishanthvijayan/CoderCalendar/pull/56

**Comment by nishanthvijayan** [comment]
I've updated the add-on to make it compatible with Firefox Quantum. Let me know if the issue is fixed.
https://addons.mozilla.org/en-US/firefox/addon/coder-calendar/
