### ISSUE TITLE
not campatible with firefox quantum (new version)

### ISSUE THREAD

**Issue by Rtwkkumar** [nishanthvijayan/CoderCalendar#55]
help man please....!!!!

**Comment by tarunz** [comment]
@nishanthvijayan Pull request 
https://github.com/nishanthvijayan/CoderCalendar/pull/56

**Comment by ramlaxman** [comment]
Still not available for Firefox 61.0.

**Comment by nishanthvijayan** [comment]
I've updated the add-on to make it compatible with Firefox Quantum. Let me know if the issue is fixed.
https://addons.mozilla.org/en-US/firefox/addon/coder-calendar/
