### ISSUE TITLE
Firefox add-on isn't compatible with the last version

### ISSUE THREAD

**Issue by ucanyiit** [nishanthvijayan/CoderCalendar#63]
![coders calneder](https://user-images.githubusercontent.com/34626070/46651870-1317b600-cbaa-11e8-99da-d9d8fdc43a40.png)

I don't know why it says"Not compatible with quantum, but I use the normal Windows version.

Firefox version 62.0.3 ( 64bit )

**Comment by nishanthvijayan** [comment]
The extension can no longer be downloaded through firefox add-on store. If you want to set it up yourself, follow the instructions here: https://github.com/nishanthvijayan/CoderCalendar-Extensions#firefox
It is fairly straightforward. Let me know if you still have any queries
