### ISSUE TITLE
Feature request: Auto-add to Google Calendar

### ISSUE THREAD

**Issue by xrisk** [nishanthvijayan/CoderCalendar#8]
While the option exists to add events to calendar, it would be nice if they would automatically be added. I am saying this because, on many of our phones and laptops, pop-up notifications come for upcoming calendar events, which may be useful when the browser is not open.

**Comment by jainendra** [comment]
I will try to add this feature if you still need it...

**Comment by nishanthvijayan** [comment]
Nope.Not everyone would want all contests to be auto-added to calendar.
